version: "3.8"

services:
  database:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - fintrack:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  core:
    image: fintrack
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy

volumes:
  fintrack:
